// Builds the browser bundle (dist/public) and the Node build of the solver (dist/solver.cjs).
// No framework: the app is a set of ordered script parts (client/src/js/*.js) concatenated into one
// classic script, exactly the way the verified prototype ran, then minified with esbuild.
import { build, transform } from 'esbuild';
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync, mkdirSync, rmSync, readdirSync, copyFileSync, existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const src = join(root, 'client/src');
const out = join(root, 'dist');
const pub = join(out, 'public');
const sha = (s) => createHash('sha256').update(s).digest('hex');
const read = (p) => readFileSync(p, 'utf8');

// only clear what this script owns: the server build (dist/server) must survive a client rebuild
rmSync(pub, { recursive: true, force: true });
rmSync(join(out, 'solver.cjs'), { force: true });
mkdirSync(join(pub, 'fonts'), { recursive: true });
mkdirSync(join(pub, 'vendor'), { recursive: true });

// ---------- catalog ----------
const catalog = JSON.parse(read(join(root, 'catalog/products.json')));
const ids = catalog.products.map((p) => p.id);
if (new Set(ids).size !== ids.length) throw new Error('catalog: duplicate product ids');
for (const p of catalog.products)
  for (const k of ['id', 'cat', 'name', 'price', 'art', 'desc', 'specs', 'tag'])
    if (p[k] === undefined) throw new Error(`catalog: product ${p.id} is missing "${k}"`);
const catalogHash = sha(JSON.stringify(catalog.products)).slice(0, 12);

const jsDir = join(src, 'js');
const partNames = readdirSync(jsDir).filter((f) => f.endsWith('.js')).sort();
const solverParts = ['00-util.js', '40-data.js', '50-solver.js'];
const solverSource = solverParts.map((f) => read(join(jsDir, f))).join('\n');
const solverVersion = sha(solverSource).slice(0, 12);

const catalogModule =
  `/* generated by client/build.mjs — do not edit; edit catalog/products.json */\n` +
  `const CATALOG_VERSION = ${JSON.stringify(catalog.version)};\n` +
  `const CATALOG_HASH = ${JSON.stringify(catalogHash)};\n` +
  `const SOLVER_VERSION = ${JSON.stringify(solverVersion)};\n` +
  `const PRODUCTS = ${JSON.stringify(catalog.products)};\n`;

// ---------- Node solver (shared with the server, tests and the benchmark) ----------
const solverExports = [
  'solve', 'revalidate', 'STATE', 'AES', 'AES_KEYS', 'AMENITY', 'FIX', 'VASTU', 'PRODUCTS', 'SCORE_WEIGHTS',
  'SLOT_CAT', 'DIR_DEG', 'vastuRating', 'vastuScore', 'bearingAt', 'dirFromDeg', 'angDiff', 'degOf',
  'SOLVER_VERSION', 'CATALOG_VERSION', 'CATALOG_HASH', 'clamp',
];
const solverCjs =
  `'use strict';\n` +
  [read(join(jsDir, '00-util.js')), catalogModule, read(join(jsDir, '40-data.js')), read(join(jsDir, '50-solver.js'))].join('\n') +
  `\nmodule.exports = { ${solverExports.join(', ')} };\n`;
writeFileSync(join(out, 'solver.cjs'), solverCjs);
try { new Function(solverCjs.replace(/module\.exports[^;]*;/, '')); } catch (e) { throw new Error('solver.cjs syntax: ' + e.message); }

// ---------- browser JS ----------
const parts = partNames.map((f) => (f === '30-catalog.js' ? catalogModule : read(join(jsDir, f))));
if (!partNames.includes('30-catalog.js')) {
  const at = partNames.findIndex((f) => f > '30-catalog.js');
  parts.splice(at < 0 ? parts.length : at, 0, catalogModule);
}
const bundleSrc = parts.join('\n;\n');
const min = await transform(bundleSrc, { minify: true, target: 'es2020', loader: 'js', legalComments: 'none' });
const jsName = `app.${sha(min.code).slice(0, 10)}.js`;
writeFileSync(join(pub, jsName), min.code);

// ---------- fonts (self-hosted so participants make no third-party requests) ----------
function fontCss(pkg, file) {
  const dir = join(root, 'node_modules', pkg);
  let css = read(join(dir, file));
  const blocks = css.match(/(\/\*[^*]*\*\/\s*)?@font-face\s*{[^}]*}/g) || [];
  const keep = blocks.filter((b) => /-latin-(ext-)?[a-z]+-(normal|italic)/.test(b) || /latin(-ext)?-(wght|opsz|standard)/.test(b));
  css = keep.join('\n');
  css = css.replace(/url\(\.\/files\/([^)]+\.woff2)\)/g, (_, f) => {
    copyFileSync(join(dir, 'files', f), join(pub, 'fonts', f));
    return `url(/fonts/${f})`;
  });
  // the woff (v1) fallbacks are not needed by any browser that runs this app
  css = css.replace(/,\s*url\(\.\/files\/[^)]+\.woff\)\s*format\("woff"\)/g, '');
  return css;
}
const fonts =
  fontCss('@fontsource-variable/inter', 'wght.css') + '\n' +
  fontCss('@fontsource-variable/bodoni-moda', 'wght.css') + '\n' +
  fontCss('@fontsource-variable/bodoni-moda', 'wght-italic.css');
const cssRaw = read(join(src, 'styles.css')).replace(/'Bodoni Moda'/g, "'Bodoni Moda Variable'").replace(/'Inter'/g, "'Inter Variable'");
const extra = existsSync(join(src, 'extra.css')) ? read(join(src, 'extra.css')) : '';
const cssMin = (await transform(fonts + '\n' + cssRaw + '\n' + extra, { loader: 'css', minify: true })).code;
const cssName = `app.${sha(cssMin).slice(0, 10)}.css`;
writeFileSync(join(pub, cssName), cssMin);

// ---------- three.js r128 (vendored from npm; no CDN at runtime) ----------
copyFileSync(join(root, 'node_modules/three/build/three.min.js'), join(pub, 'vendor/three.min.js'));

// ---------- html ----------
const favicon = "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'%3E%3Crect width='32' height='32' rx='6' fill='%2314181D'/%3E%3Ctext x='16' y='22' text-anchor='middle' font-family='serif' font-size='18' fill='%23C9A574'%3EK%3C/text%3E%3C/svg%3E";
const html = `<!DOCTYPE html>
<html lang="en" data-theme="light">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>KOHLER · Gracious Living &amp; the AI Bathroom Designer</title>
<meta name="description" content="Plan a bathroom around your room, your budget and your orientation. A Kohler research prototype.">
<link rel="icon" href="${favicon}">
<link rel="stylesheet" href="/${cssName}">
</head>
<body>
<a class="skip" href="#" id="skipLink">Skip to content</a>
${read(join(src, 'body.html'))}
<script defer src="/${jsName}"></script>
</body>
</html>
`;
writeFileSync(join(pub, 'index.html'), html);
writeFileSync(join(pub, 'build.json'), JSON.stringify({ js: jsName, css: cssName, catalogVersion: catalog.version, catalogHash, solverVersion }, null, 2));
console.log(`built ${jsName} (${(min.code.length / 1024).toFixed(0)} KB), ${cssName}, solver ${solverVersion}, catalog ${catalog.version}/${catalogHash}`);
